Introduction to NumPy

Problem 1

In [9]:
A = np.array([[3,-1,4],
             [1,5,-9]])


In [10]:
B = np.array([[2,6,-5,3],
              [5,-8,9,7],
              [9,-3,-2,-3]])

In [13]:
A@B


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2

In [29]:
def prob2():
    A = np.array([[3,1,4],
             [1,5,9],
             [-5,3,1]])
    return (-1*(A@A@A)+9*(A@A)-15*A)

In [30]:
prob2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
prob2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 3


In [81]:
def prob3():
    I = np.ones((7,7))
    A = np.triu(I)
    print(A)
    J = 6* np.ones((7,7))
    K = np.triu(J)
    L = K -1
    M = np.diag([-6,-6,-6,-6,-6,-6,-6])
    B = M+L
    print(B)
    C = A@B@A
    type(C)
    print(C.dtype)
    C = C.astype(np.int64)
    return C
    

In [82]:
prob3()

[[1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[-1.  5.  5.  5.  5.  5.  5.]
 [-1. -1.  5.  5.  5.  5.  5.]
 [-1. -1. -1.  5.  5.  5.  5.]
 [-1. -1. -1. -1.  5.  5.  5.]
 [-1. -1. -1. -1. -1.  5.  5.]
 [-1. -1. -1. -1. -1. -1.  5.]
 [-1. -1. -1. -1. -1. -1. -1.]]
float64


array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

Problem 4

In [83]:
def prob4(A):
    np.copy(A)
    mask= A<0
    A[mask]=0
    return A

In [86]:
prob4(np.array([1,-2,3,-4]))

array([1, 0, 3, 0])

Problem 5

In [124]:
def prob5():
    A = np.array([[0,2,4],
                  [1,3,5]])
    B = np.array([[3,0,0],
                  [3,3,0],
                  [3,3,3]])
    C = np.diag([-2, -2, -2])
    D = np.zeros((3,3))
    AT = A.T
    I = np.eye(3)
    E = np.vstack((D,A,B))
    F = np.zeros((2,2))
    F2 = np.zeros((3,2))
    F3 = np.zeros((2,3))
    G = np.vstack((AT,F,F2))
    H = np.vstack((I,F3,C))
    J = np.hstack((E,G,H))
    return J

In [125]:
prob5()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

The Standard Library

In [3]:
def prob1(L):
    A = min(L)
    B = max(L)
    C = sum(L) / len(L)
    return A, B, C

In [6]:
B = int(2)

In [8]:
C = B


In [10]:
C = C+1

In [11]:
C

3

In [12]:
B

2

In [13]:
D = str(2)

In [22]:
D


'2'

In [15]:
E=D

In [16]:
E

'2'

In [18]:
F = str(1)

In [19]:
E= E+F

In [20]:
E

'21'

In [23]:
D


'2'

In [28]:
list = [1,2,3]

In [29]:
list2=list

In [32]:
list2.append(4)

In [35]:
tup = (1,2,3)

In [37]:
tup2 = tup

In [39]:
set = {1,2,3}

In [41]:
set2 = set

In [45]:
set3 = {4}

In [47]:
set2.add(4)

In [48]:
set2

{1, 2, 3, 4}

In [49]:
set

{1, 2, 3, 4}

Sets and lists are mutable
Tuples, integers, and strings are immutable. 

Problem 3

In [3]:
import calculator as cl

In [4]:
def hyp(a,b):
    A = cl.myproduct(a,a)
    B = cl.myproduct(b,b)
    C = cl.mysum(A,B)
    D = cl.sqrt(C)
    return D

In [5]:
hyp(3,4)

5.0

Problem 4

In [56]:
from itertools import combinations
def prob4(A):
    powerA = []
    for i in range(len(A)+1):
        addSet = combinations(A,i)
        for items in addSet:
            powerA.append(set(items))
            
    return powerA
    
    
  
    

In [57]:
prob4([1,2,3])

[set(), {1}, {2}, {3}, {1, 2}, {1, 3}, {2, 3}, {1, 2, 3}]