Kendra Robbins

## Introduction to Numpy

In [105]:
import numpy as np

Problem 1

In [9]:
A = np.array([[3,-1,4],
             [1,5,-9]])


In [10]:
B = np.array([[2,6,-5,3],
              [5,-8,9,7],
              [9,-3,-2,-3]])

In [13]:
A@B


array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

Problem 2

In [29]:
def prob2():
    A = np.array([[3,1,4],
             [1,5,9],
             [-5,3,1]])
    return (-1*(A@A@A)+9*(A@A)-15*A)

In [30]:
prob2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
prob2()

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Problem 3


In [81]:
def prob3():
    I = np.ones((7,7))
    A = np.triu(I)
    print(A)
    J = 6* np.ones((7,7))
    K = np.triu(J)
    L = K -1
    M = np.diag([-6,-6,-6,-6,-6,-6,-6])
    B = M+L
    print(B)
    C = A@B@A
    type(C)
    print(C.dtype)
    C = C.astype(np.int64)
    return C
    

In [82]:
prob3()

[[1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[-1.  5.  5.  5.  5.  5.  5.]
 [-1. -1.  5.  5.  5.  5.  5.]
 [-1. -1. -1.  5.  5.  5.  5.]
 [-1. -1. -1. -1.  5.  5.  5.]
 [-1. -1. -1. -1. -1.  5.  5.]
 [-1. -1. -1. -1. -1. -1.  5.]
 [-1. -1. -1. -1. -1. -1. -1.]]
float64


array([[ -7,  -8,  -3,   8,  25,  48,  77],
       [ -6, -12, -12,  -6,   6,  24,  48],
       [ -5, -10, -15, -14,  -7,   6,  25],
       [ -4,  -8, -12, -16, -14,  -6,   8],
       [ -3,  -6,  -9, -12, -15, -12,  -3],
       [ -2,  -4,  -6,  -8, -10, -12,  -8],
       [ -1,  -2,  -3,  -4,  -5,  -6,  -7]])

Problem 4

In [16]:
def prob4(A):
    np.copy(A)
    mask= A<0
    A[mask]=0
    return A

In [86]:
prob4(np.array([1,-2,3,-4]))

array([1, 0, 3, 0])

Problem 5

In [124]:
def prob5():
    A = np.array([[0,2,4],
                  [1,3,5]])
    B = np.array([[3,0,0],
                  [3,3,0],
                  [3,3,3]])
    C = np.diag([-2, -2, -2])
    D = np.zeros((3,3))
    AT = A.T
    I = np.eye(3)
    E = np.vstack((D,A,B))
    F = np.zeros((2,2))
    F2 = np.zeros((3,2))
    F3 = np.zeros((2,3))
    G = np.vstack((AT,F,F2))
    H = np.vstack((I,F3,C))
    J = np.hstack((E,G,H))
    return J

In [125]:
prob5()

array([[ 0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  3.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  4.,  5.,  0.,  0.,  1.],
       [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
       [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
       [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

Problem 6


In [108]:
def prob6(A):
    
    i, j = np.shape(A)
    rowSums = np.sum(A, axis=1).reshape((j,1))
    B = A / rowSums
    
    return B


Problem 7

In [110]:
def problem_7():
    grid = np.load("grid.npy")
    
    horizontalMax = np.max(grid[:,:-3] * grid[:,1:-2] * grid[:,2:-1] * grid[:,3:])
    verticalMax = np.max(grid[:-3,:] * grid[1:-2,:] * grid[2:-1,:] * grid[3:,:])
    rightDiagonalMax = np.max(grid[:-3,:-3] * grid[1:-2,1:-2] * grid[2:-1,2:-1] * grid[3:,3:])
    leftDiagonalMax = np.max(grid[3:,:-3] * grid[2:-1,1:-2] * grid[1:-2,2:-1] * grid[:-3,3:])
    
    return max(horizontalMax, verticalMax, rightDiagonalMax, leftDiagonalMax)
   


## The Standard Library

In [3]:
def prob1(L):
    A = min(L)
    B = max(L)
    C = sum(L) / len(L)
    return A, B, C

In [6]:
B = int(2)

In [8]:
C = B


In [10]:
C = C+1

In [11]:
C

3

In [12]:
B

2

In [13]:
D = str(2)

In [22]:
D


'2'

In [15]:
E=D

In [16]:
E

'2'

In [18]:
F = str(1)

In [19]:
E= E+F

In [20]:
E

'21'

In [23]:
D


'2'

In [28]:
list = [1,2,3]

In [29]:
list2=list

In [32]:
list2.append(4)

In [35]:
tup = (1,2,3)

In [37]:
tup2 = tup

In [39]:
set = {1,2,3}

In [41]:
set2 = set

In [45]:
set3 = {4}

In [47]:
set2.add(4)

In [48]:
set2

{1, 2, 3, 4}

In [49]:
set

{1, 2, 3, 4}

Sets and lists are mutable
Tuples, integers, and strings are immutable. 

Problem 3

In [3]:
import calculator as cl

In [4]:
def hyp(a,b):
    A = cl.myproduct(a,a)
    B = cl.myproduct(b,b)
    C = cl.mysum(A,B)
    D = cl.sqrt(C)
    return D

In [5]:
hyp(3,4)

5.0

Problem 4

In [56]:
from itertools import combinations
def prob4(A):
    powerA = []
    for i in range(len(A)+1):
        addSet = combinations(A,i)
        for items in addSet:
            powerA.append(set(items))
            
    return powerA
    
    
  
    

In [57]:
prob4([1,2,3])

[set(), {1}, {2}, {3}, {1, 2}, {1, 3}, {2, 3}, {1, 2, 3}]

## Unit Testing

Problem 1: see test_smallest_factor.py

In [ ]:
def smallest_factor(n):
    """Return the smallest prime factor of the positive integer n."""
    if n == 1: return 1
    for i in range(2, int(n**.5) + 1):
        if n % i == 0: return i
    return n

Problem 2: see test_month_length.py

Problem 3: see test_operate.py

Problem 4: fixed addition, subtraction. See test_fractions.py

In [67]:
class Fraction(object):
    """Reduced fraction class with integer numerator and denominator."""
    def __init__(self, numerator, denominator):
        if denominator == 0:
            raise ZeroDivisionError("denominator cannot be zero")

        elif type(numerator) is not int or type(denominator) is not int:
            raise TypeError("numerator and denominator must be integers")
    
        def gcd(a,b):
            while b != 0:
                a, b = b, a % b
            return a

        common_factor = gcd(numerator, denominator)
        self.numer = numerator // common_factor
        self.denom = denominator // common_factor

    def __str__(self):
        if self.denom != 1:
            return "{} / {}".format(self.numer, self.denom)
        
        else:
            return str(self.numer)

    def __float__(self):
        return self.numer / self.denom

    def __eq__(self, other):
        if type(other) is Fraction:
            return self.numer==other.numer and self.denom==other.denom
        else:
            return float(self) == other

    def __add__(self, other):
        return Fraction(self.numer*other.denom + self.denom*other.numer, self.denom*other.denom)

    def __sub__(self, other):
        return Fraction(self.numer*other.denom - self.denom*other.numer, self.denom*other.denom)

    def __mul__(self, other):
        return Fraction(self.numer*other.numer, self.denom*other.denom)

    def __truediv__(self, other):
        if self.denom*other.numer == 0:
            raise ZeroDivisionError("cannot divide by zero")

        return Fraction(self.numer*other.denom, self.denom*other.numer)

In [68]:
A = Fraction(2,3)

In [69]:
B = Fraction(1,3)

In [70]:
str(A+B)

'1'

In [71]:
str(A-B)

'1 / 3'

In [75]:
def set_up_fractions():
    frac_1_3 = Fraction(1, 3)
    frac_1_2 = Fraction(1, 2)
    frac_n2_3 = Fraction(-2, 3)
    return frac_1_3, frac_1_2, frac_n2_3

def test_fraction_init(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3 = set_up_fractions
    assert frac_1_3.numer == 1
    assert frac_1_2.denom == 2
    assert frac_n2_3.numer == -2
    frac = Fraction(30, 42) # 30/42 reduces to 5/7.
    assert frac.numer == 5
    assert frac.denom == 7

def test_fraction_str(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3 = set_up_fractions
    assert str(frac_1_3) == "1/3"
    assert str(frac_1_2) == "1/2"
    assert str(frac_n2_3) == "-2/3"
    return print(str(frac_1_3))

def test_fraction_float(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3 = set_up_fractions
    assert float(frac_1_3) == 1 / 3.
    assert float(frac_1_2) == .5
    assert float(frac_n2_3) == -2 / 3.

def test_fraction_eq(set_up_fractions):
    frac_1_3, frac_1_2, frac_n2_3 = set_up_fractions
    assert frac_1_2 == Fraction(1, 2)
    assert frac_1_3 == Fraction(2, 6)
    assert frac_n2_3 == Fraction(8, -12)


    


Problem 5

In [ ]:
#@pytest.fixture
def set_up_hands():
    hand1 = ["1022", "1122", "0100", "2021", "0010", "2201",
             "2111", "0020", "1102", "0210", "2110", "1020"]
    Not12 = ["0000"]
    NotUnique = ["0000", "0000", "0000", "0000", "0000", "0000",
                     "0000", "0000", "0000", "0000", "0000", "0000"]
    WrongDigits = ["00000", "1122", "0100", "2021", "0010", "2201",
                       "2111", "0020", "1102", "0210", "2110", "1020"]
    NotMod3 = ["3022", "1122", "0100", "2021", "0010", "2201",
                     "2111", "0020", "1102", "0210", "2110", "1020"]
    return hand1, not12, NotUnique, WrongDigits, NotMod3
    
    
def test_count_sets():
    
    hand1, not12, NotUnique, WrongDigits, NotMod3 = set_up_hands
    assert func.count_sets(hand1) = 6
    pytest.raises(ValueError, func.count_sets, cards = Not12)
    pytest.raises(ValueError, func.count_sets, cards = NotMod3)
    pytest.raises(ValueError, func.count_sets, cards = NotUnique)
    pytest.raises(ValueError, func.count_sets, cards = WrongDigits)
    
def test_is_set():
    
    assert is_set("1010", "0101", "2222") = True
    assert is_set("1111", "0000", "1111") = False
    assert is_set("1000", "1121", "1212") = True
    
    

# Problem 6 - - - - - needs revision

In [79]:
from itertools import combinations, permutations

In [7]:
def count_sets(cards):
    
    if len(cards) != 12:
        raise ValueError("hand must contain 12 cards")
    if len(cards)>len(set(cards)):
        raise ValueError("all cards must be unique")
    for card in cards:
        if len(card) != 4:
            raise ValueError("each card must be described by 4 numbers")
    for card in cards:
        for num in card:
            if num not in "012":
                raise ValueError("each card must contain only numbers 0, 1, 2")
                
                
    numSets = 0
    combs = list(combinations(cards, 3))
    for potSet in combs:
        if is_set(str(potSet[0]), str(potSet[1]), str(potSet[2])):
            numSets += 1

    return numSets
    
    
def is_set(a,b,c):
    
    firstdigits = True
    seconddigits = True
    thirddigits = True
    fourthdigits = True
    
    set_first = {a[0], b[0], c[0]}
    set_second = {a[1], b[1], c[1]}
    set_third = {a[2], b[2], c[2]}
    set_fourth = {a[3], b[3], c[3]}
    
    A = [1,3]
    
    if len(set_first) not in A:
        firstdigits = False
    if len(set_second) not in A:
        seconddigits = False
    if len(set_third) not in A:
        thirddigits = False
    if len(set_fourth) not in A:
        fourthdigits = False
        
    print(firstdigits)
    print(fourthdigits)
        
    if firstdigits and seconddigits and thirddigits and fourthdigits:
        is_set = True
        
    else:
        is_set = False
        
    print(is_set)
        
    return is_set

In [8]:
is_set("0000","0000","0000")

True
True
True


True

## Object Oriented

Problem 1&3

In [288]:
class Backpack:
    
    def __init__(self, name, color, max_size=5): 
        
        #name, color, max_size are attributes 
        # __init__ is the constructor, which is a method
        
        
        self.name=name
        self.contents = []
        
        self.color = color
        self.max_size = max_size
        
    def put(self, item): #a method that adds 'item' to contents if possible
        
        if len(self.contents) >= self.max_size : 
            
            # if the bag is full, 'item' is not added to contents and "No Room!" is printed.
            print("No Room!")
        
        if len(self.contents) < self.max_size:
            
            # if there is room for 'item' in the backpack, 'item' is added.
            
            self.contents.append(item)
        
    def take(self, item):
        
        #'item' is removed from the backpack
        
        self.contents.remove(item)
        
    def dump(self): 
        
        #removes all contents from the backpack
        self.contents = []
        
    def __eq__(self, other):
    
        #determine when two backpacks are equal.
        #two backpacks are equal iff their names, number of contents, and color are the same. 
        
        if self.name != other.name:
            return False 
        if len(self.contents) != len(other.contents):
            return False
        if self.color != other.color:
            return False
        else:
            return True
        
        
    def __str__(self):
        
        string = f'''
            Owner: \t {self.name}
            Color: \t {self.color}
            Size: \t{len(self.contents)}
            Max Size: \t{self.max_size}
            Contents: \t{self.contents}
        '''
        return string
        
        

In [289]:
def test_backpack():
    testpack = Backpack("Barry", "black")
    if testpack.name != "Barry":
        print("Backpack.name assigned incorrectly.")

    for item in ["pencil", "pen", "paper", "computer"]:
        testpack.put(item)

    print(testpack.contents)

In [290]:
test_backpack()

['pencil', 'pen', 'paper', 'computer']


In [291]:
bag = Backpack("Kendra", "green")

In [292]:
bag.put("book")

In [293]:
print(bag)


            Owner: 	 Kendra
            Color: 	 green
            Size: 	1
            Max Size: 	5
            Contents: 	['book']
        


Problem 2 

In [52]:
class Jetpack(Backpack):
    
    #Jetpack is a subclass of Backpack with attributes name, color, max_size, and fuel.
    
    def __init__(self, name, color, max_size=2, fuel=10):
        
        Backpack.__init__(self, name, color, maxsize=3, fuel=10)
        
        self.fuel=fuel
        
        def fly(x): #x is the amount of fuel needed for flying.
            if self.fuel<x:  #the jetpack does not fly if there is not enough fuel.
                print("Not enough fuel!")
            
            else:   # fuel level decreases by the amount needed for flying
                self.fuel = self.fuel-x
                
        def dump(): #dump empties contents and fuel 
            self.contents = []
            self.fuel = 0

Problem 4

In [186]:
class ComplexNumber():
    
    def __init__(self, a, b):
    
        self.real = a
        self.imag = b
    
    def conjugate(self, a, b): 
        
        return ComplexNumber(self.real, -(self.imag))
    
    def __str__(self):
        
        if self.imag >=0:
            string = str( "(" + str(self.real) + '+' + str(self.imag) + 'j'+')')
            return string
        
        if self.imag <0:
            string = str('('+str(self.real)+'-'+str(-self.imag)+'j'+')')
            return string
        
    def __abs__(self):
        
        C = (self.real)**2+(self.imag)**2
        D = C**(.5)
        return D
    
    def __eq__(self, other):
        
        if self.real != other.real:
            return False
        if self.imag != other.imag:
            return False
        else:
            return True 
        
    def __add__(self, other):
        
        real = self.real + other.real
        imag = self.imag + other.imag 
        
        return ComplexNumber(real, imag)
    
    def __sub__(self, other):
        
        real = self.real - other.real
        imag = self.imag - other.imag
        
        return ComplexNumber(real, imag)
    
    def __mul__(self, other):
        
        real = self.real * other.real - self.imag * other.imag
        imag = self.real * other.imag + self.imag * other.real
        
        return ComplexNumber(real, imag)
    
    def __truediv__(self, other):

        if other.real == 0 and other.imag == 0:
            raise ZeroDivisionError("cannot divide by zero")
        
        denom = other.real**2 + other.imag**2
        real = (self.real * other.real + self.imag * other.imag) / denom
        imag = (self.imag * other.real - self.real * other.imag) / denom
        
        return ComplexNumber(real, imag)

In [187]:
A = ComplexNumber(2,3)

In [188]:
print(A)

(2+3j)


In [189]:
B = ComplexNumber(2,-3)

In [190]:
print(B)

(2-3j)


In [191]:
abs(B)

3.605551275463989

In [192]:
A == B

False

In [194]:
print(A*B)

(13+0j)


In [299]:
def test_ComplexNumber(a,b):
    py_cnum, my_cnum = complex(a,b), ComplexNumber(a,b)
    
    # Validate the constructor.
    if my_cnum.real != a or my_cnum.imag != b:
        print("__init__() set self.real and self.imag incorrectly")
    
    # Validate conjugate() by checking the new number's imag attribute.
    if py_cnum.conjugate().imag != my_cnum.conjugate().imag:
        print("conjugate() failed for", py_cnum)
    
    # Validate __str__().
    if str(py_cnum) != str(my_cnum):
        print("__str__() failed for", py_cnum)
        
   

## Exceptions and File Input/Output

Problem 1

In [20]:
def arithmagic():
    step_1 = input("Enter a 3-digit number where the first and last digits differ by 2 or more: ")
    
    if len(step_1) !=3:
        raise ValueError("step_1 should be a 3 digit number")
        
    if abs(int(step_1[0]) - int(step_1[2])) <2 :
        raise ValueError("first and last digits of step_1 must differ by 2 or more")
    
    step_2 = input("Enter the reverse of the first number, obtained by reading it backwards: ")
    
    if step_2 != step_1[::-1]:
        raise ValueError("step_2 is not the reverse of step_1")
    
    step_3 = input("Enter the positive difference of these numbers: ")
    
    if int(step_3) != abs(int(step_1)-int(step_2)):
        raise ValueError("step_3 is not the positive difference of step_1 and step_2")
    
    step_4 = input("Enter the reverse of the previous result: ")
    
    if step_4 != step_3[::-1]:
        raise ValueError("step_4 is not the reverse of step_3")
    
    print(str(step_3), "+", str(step_4), "= 1089 (ta-da!)")

In [22]:
arithmagic()

Enter a 3-digit number where the first and last digits differ by 2 or more: 125
Enter the reverse of the first number, obtained by reading it backwards: 521
Enter the positive difference of these numbers: 396
Enter the reverse of the previous result: 693
396 + 693 = 1089 (ta-da!)


Problem 2

In [23]:
from random import choice 

In [39]:
def random_walk(max_iters=100):
    walk = 0
    directions = [1, -1]
    
    try:
        for i in range(int(max_iters)):
            walk += choice(directions)
        
    except KeyboardInterrupt:
        print("Process interrupted at iteration", ind)
        
    else:
        print("Process completed.")
        
    finally:
        print("Value of walk is", walk)
        return walk

# Problem 3 & 4

In [ ]:
class ContentFilter():
    """
    
    Attributes:
        filename (str): the name of the file to be read
        contents (str): the contents of the file "filname"
        totalChar (int): the total number of characters in the file
        totalAlph (int): the total number of letters in file
        totalNum (int): the total number of digits in file
        totalSpaces (int): the total number of spaces in file
        totalLines (int): the total number of lines in file
        
     """
    
    def __init__(self, filename):
        """ Construct a file.
        
        Paramters:
            filename (str): the name of the file to read
        
        """
        
        correctFile = False
        self.filename = filename
        
        while not correctFile:
            try:
                myFile = open(self.filename, 'r')
            except FileNotFoundError as e:
                self.filename = input("Please enter a valid file name: ")
                continue
            except TypeError as e:
                self.filename = input("Please enter a valid file name: ")
                continue
            except OSError as e:
                self.filename = input("Please enter a valid file name: ")
                continue
            else:
                correctFile = True
                  
        self.filename = filename
        self.lines = myFile.readlines()
        
        content = ""
        for line in self.lines:
            content += line
            
        self.contents = content
            
        self.totalLines = sum(1 for line in open(filename))
        myFile.close()
        
        
        self.totalChar = len(self.contents)
        self.totalAlph = sum(char.isalpha() for char in self.contents)
        self.totalNum = sum(char.isdigit() for char in self.contents)
        self.totalSpaces = sum(char.isspace() for char in self.contents)
        
    def uniform(self, outfile, mode='w', case='upper'):
        """Write the data to the outfile with uniform case.
        
        Parameters:
            outfile (str): the name of the file to write to
            mode (str): the file access mode, either 'w', 'x', or 'a'; 
                        defaults to 'w'
            case (str): the case in which the text will be written to outfile; 
                        defaults to 'upper'
            
        """
        
        if mode not in ['w', 'x', 'a']:
            raise ValueError("Mode must be either w, x, or a.")
        if case not in ['upper', 'lower']:
            raise ValueError("Case must be either upper or lower.")
        try:
            myFileOut = open(outfile, mode)

            if case == "upper":
                for line in self.contents:
                    myFileOut.write(line.upper())
            elif case == "lower":
                for line in self.contents:
                    myFileOut.write(line.lower())
        finally:
            myFileOut.close()
            
    def reverse(self, outfile, mode='w', unit='line'):
        """Write the data to the outfile in reverse order.
        
        Parameters:
            outfile (str): the name of the file to write to
            mode (str): the file access mode, either 'w', 'x', or 'a'; 
                        defaults to 'w'
            unit (str): If unit="word", reverse the ordering of the words in each line, 
                        but write the lines in the same order as the original file. 
                        If unit="line", reverse the ordering of the lines, 
                        but do not change the ordering of the words on each individual line. 
                        If unit is not one of these two values, raise a ValueError. 
                        Defaults to "line."
            
        """    
        if mode not in ['w', 'x', 'a']:
            raise ValueError("Mode must be either w, x, or a.")
        
        if unit not in ["line", "word"]:
            raise ValueError("unit must be either line or word")
            
        try:
            myFileOut = open(outfile, mode)

            if unit == "line":
                for i in range(len(self.lines)):
                    myFileOut.write(self.lines[-(i+1)])
            elif unit == "word":
                for line in self.lines: 
                    words = line.split()
                    line_rev = " ".join(reversed(words)) + '\n'
                    myFileOut.write(line_rev)
        finally:
            myFileOut.close()       
        
    def transpose(self, outfile, mode='w'):
        """Write a transposed version of the data to the outfile.
        This means writing the first word of each line of the data to the
        first line of the new file, the second word of each line of the data
        to the second line of the new file, and so on. 
        
        We assume that there are an equal number of words on each line
        of the input file.
        
        Parameters:
            outfile (str): the name of the file to write to
            mode (str): the file access mode, either 'w', 'x', or 'a'; 
                        defaults to 'w'
            
        """   
        
        if mode not in ['w', 'x', 'a']:
            raise ValueError("Mode must be either w, x, or a.")
            
        try:
            myFileOut = open(outfile, mode)
            wordMat = []
            
            for line in self.lines:
                words = line.split()
                wordMat.append(words)
            
            wordMat2 = np.array(wordMat)
            wordMatT = wordMat2.T
            
            for row in wordMatT:
                nextline = " ".join(row)
                myFileOut.write(nextline + "\n")
            
        finally:
            myFileOut.close()
        
    def __str__(self):
        """Returns a string with characters of the file."""
        
        string = ("Source file:\t\t\t" + self.filename +
                 "\nTotal characters:\t\t" + str(self.totalChar) +
                 "\nAlphabetic characters:\t\t" + str(self.totalAlph) +
                 "\nNumerical characters:\t\t" + str(self.totalNum) +
                 "\nWhitespace characters:\t\t" + str(self.totalSpaces) +
                 "\nNumber of lines:\t\t" + str(self.totalLines))
        
        return string